name: ThrowinPeeps
version: 1.1
main: com.garsooon.throwinpeeps.ThrowinPeepsPlugin
description: Pick up and throw players. Thrown players take no fall damage.
author: Garsooon

commands:
  throwinpeeps:
    description: Toggle whether you can pickup players.
    permission: throwinpeeps.toggle
    usage: /throwinpeeps

permissions:
  throwinpeeps.toggle:
    description: Allows toggling the throw ability on/off.
    default: op
